### ISSUE TITLE
Download error when using a SOCKS proxy

### ISSUE THREAD

**Issue by immadolf** [tldr-pages/tlrc#71]
i install tlrc by homebrew on macos. When i input `tldr fd` , it show 
```txt
info: cache is empty, downloading...
info: downloading 'tldr.sha256sums'... error: https://github.com/tldr-pages/tldr/releases/latest/download/tldr.sha256sums: Connection Failed: Connect error: SOCKS feature disabled.
```

how can i fix it?

**Comment by acuteenvy** [comment]
It seems like SOCKS support is disabled by default in the HTTP client used by tlrc. I'll try to fix this later in a new release.

How did you configure the proxy?

**Comment by immadolf** [comment]
I executed the `export` command in the shell. I did not add it to the `.zshrc` file.

**Comment by acuteenvy** [comment]
> So do I need to download in a shell without proxy configuration?

For now, this is the only way. I'll fix it in a new release.

**Comment by immadolf** [comment]
> > So do I need to download in a shell without proxy configuration?
> 
> For now, this is the only way. I'll fix it in a new release.

thks.

**Comment by kbdharun** [comment]
Reopening the issue, as a reminder to fix it before the next release. (**Note**: It will be closed by the respective maintainer when committing the fix)

**Comment by acuteenvy** [comment]
Fixed in https://github.com/tldr-pages/tlrc/commit/9abe507f85a76d121ccf428108fc1d9e85d443f9.
