### ISSUE TITLE
Feature request: Add relative paths for cache dir

### ISSUE THREAD

**Issue by mahume** [tldr-pages/tlrc#80]
On MacOS with tlrc installed via homebrew.

Neither of these work:
```
[cache]
dir = "~/.cache/tldr"
# OR
dir = "$HOME/.cache/tldr"
```

It just dumps a new cache directory into the working directory where the `tldr` command was used with the path specified in the dir field.

However, using an absolute path seems to work:
```
[cache]
dir = "/Users/<my_username>/.cache/tldr"
```

Would be nice to support relative paths for multi device usage.

**Comment by acuteenvy** [comment]
Thanks for the issue.
Support for relative paths has been added in https://github.com/tldr-pages/tlrc/commit/4a55d5b97fabd6176adb8056e2170152dac52c61 and will be a part of the next release.
