### ISSUE TITLE
[Feature Request] Allow config path to be specified via environment variable

### ISSUE THREAD

**Issue by HUMORCE** [tldr-pages/tlrc#89]
I prefer to put the config file in a manageable dir, e.g.: `~/.config/tlrc/config.toml`

**Comment by acuteenvy** [comment]
tlrc uses the [`dirs`](https://github.com/dirs-dev/dirs-rs) crate, specifically [this function](https://docs.rs/dirs/5.0.1/dirs/fn.config_dir.html) to get the default config dir. It supports `$XDG_CONFIG_HOME` on Linux.
What OS are you on?

Regardless of that, there is a `--config` command-line option that you can use to override the default path.
Alias `tldr` to `tldr --config path/to/file` in your shell if you want to make this permanent.

**Comment by acuteenvy** [comment]
I wanted to try reporting this upstream, but it seems that people have requested this feature multiple times and they keep rejecting every request they get. This has been discussed in https://github.com/dirs-dev/directories-rs/issues/47.

Anyway, it's pretty easy to just do this manually. What about the cache directory? Currently it's `~/Library/Caches` on macOS, should it be changed to follow the XDG spec too? I've never used macOS, I don't really know the standards there. What do other command-line programs do? `$XDG_CACHE_HOME` and `$HOME/.cache` like on Linux?

**Comment by acuteenvy** [comment]
I added support for an environment variable, `TLRC_CONFIG`.

I'll still consider using XDG by default on macOS, since I found a lot of similar requests in other repositories. `~/Library/Application Support` will still be supported though.
